# Generated by Django 4.2.17 on 2025-01-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_link', models.URLField(blank=True, null=True)),
                ('series_title', models.CharField(max_length=255)),
                ('released_year', models.PositiveIntegerField()),
                ('certificate', models.CharField(blank=True, max_length=10, null=True)),
                ('runtime', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=100)),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('overview', models.TextField()),
                ('meta_score', models.PositiveIntegerField(blank=True, null=True)),
                ('director', models.CharField(max_length=255)),
                ('star1', models.CharField(max_length=255)),
                ('star2', models.CharField(max_length=255)),
                ('star3', models.CharField(max_length=255)),
                ('star4', models.CharField(max_length=255)),
                ('no_of_votes', models.PositiveIntegerField()),
                ('gross', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-released_year'],
            },
        ),
    ]
